import episodesJson from '@/data/episodes.json';
import archiveJson from '@/data/episodes-archive.json';
import slugMap from '@/data/episode-slugs.json';

/**
 * Podcast episode data, migrated from the podcast SPA in the 2026-08-24 one-site
 * consolidation.
 *
 * ⚠️ EPISODES ARE ADDRESSED BY SLUG. The canonical route is `/podcast/:slug`, where the
 * slug is derived from the Libsyn episode URL and is stable across feed regeneration.
 *
 * The original consolidation carried the SPA's positional `/podcast/:index` contract
 * over unchanged, which was fragile in a specific way: `scripts/rss-to-episodes.py`
 * regenerates the array newest-first, PREPENDING new episodes, so one refresh shifted
 * every existing URL onto a different show — silently, with no 404. The slug migration
 * (see `src/data/episode-slugs.json`) removes that failure mode.
 *
 * The legacy numeric URLs are still public and indexed, so they are NOT dropped: the
 * frozen index→slug map drives permanent redirects from `/podcast/:index` to the
 * episode's slug. `src/data/episode-url-lock.json` remains the frozen record of what
 * each legacy index meant, and its guard test still enforces that mapping.
 *
 * Audio and artwork stay on Libsyn (`traffic.libsyn.com`, `static.libsyn.com`). Podcast
 * DISTRIBUTION is not part of this consolidation and no redirect rule may match a
 * libsyn hostname.
 */

export interface Episode {
  /** Stable URL slug, derived from the Libsyn episode URL. */
  slug: string;
  title: string;
  /** ISO date (YYYY-MM-DD) parsed from the RSS pubDate */
  date: string;
  description: string;
  /** e.g. "09:34" */
  duration: string;
  /** Libsyn episode page URL */
  link: string;
  /** Direct MP3 from the RSS enclosure — stays on traffic.libsyn.com */
  audioUrl: string;
  /** Per-episode artwork from the feed, if present */
  image: string | null;
  /** Local thumbnail in /public/episodes */
  thumb: string;
  /** Full untruncated description for the detail page */
  body: string;
}

interface SlugEntry {
  index: number;
  slug: string;
  title: string;
  /** Libsyn episode URL — the stable identity a slug is bound to. */
  link: string;
}

const slugEntries = (slugMap as { episodes: SlugEntry[] }).episodes;

/**
 * Slug lookup keyed by the Libsyn episode URL.
 *
 * ⚠️ BOUND BY LINK, NEVER BY ARRAY POSITION. `rss-to-episodes.py` regenerates
 * episodes.json newest-first, PREPENDING new episodes — the same shift that made the
 * old `/podcast/:index` URLs unsafe. Binding a slug to `episodes[i]` would reintroduce
 * that bug one layer down: after a refresh every episode would silently inherit the
 * previous occupant's slug, so a published URL would serve a different show. The
 * Libsyn link is the episode's real identity and does not move.
 */
const slugByLink = new Map(slugEntries.map((e) => [e.link, e.slug]));

/** Fallback for an episode added after the map was frozen — same rule as the generator. */
function deriveSlug(link: string, title: string): string {
  let s = (link.split('/').pop() ?? '').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  if (!s) s = title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return s.replace(/-+/g, '-').replace(/^-+/, '').replace(/-+$/, '').slice(0, 90).replace(/-+$/, '');
}

/**
 * Episodes with their stable slug attached. The slug lives in a separate frozen map
 * rather than in `episodes.json` so that regenerating the feed (which rewrites
 * episodes.json wholesale) cannot silently drop or rewrite a published slug.
 *
 * A new episode not present in the frozen map derives its slug from its own link, so
 * a feed refresh publishes it correctly without a code change. Re-freeze the map
 * (see tasks/CUTOVER-podcast-routes.md) to bring it under the guard test.
 */
const withSlug = (episode: Omit<Episode, 'slug'>): Episode => ({
  ...episode,
  slug: slugByLink.get(episode.link) ?? deriveSlug(episode.link, episode.title),
});

/**
 * The rolling RSS window: the 150 most recent episodes, regenerated by
 * `rss-to-episodes.py`. Anything older than its cutoff drops out of this file.
 */
const rolling: Episode[] = (episodesJson as Omit<Episode, 'slug'>[]).map(withSlug);

/**
 * HISTORICAL SUPPLEMENT — episodes that have fallen out of the rolling window but are
 * still publicly linked, so they still need a canonical page.
 *
 * These came in through the curated featured-episode set (`/podcast/featured/:index`),
 * which reached back to 2019 while the RSS window starts at 2026-02-03. Redirecting
 * them to the index would have discarded real page-level content and read as a soft
 * 404, so they are promoted to first-class episodes instead.
 *
 * They are keyed by their immutable Libsyn link and are NOT rewritten by a feed
 * refresh. If an archived episode later reappears in the rolling feed, the rolling
 * copy wins and the archive entry is dropped — see the dedupe below — so the merge can
 * never mint two pages for one episode.
 */
const archive: Episode[] = (archiveJson as Omit<Episode, 'slug'>[]).map(withSlug);

/**
 * All episodes: the rolling feed plus the historical supplement, deduplicated by
 * Libsyn link and sorted newest-first.
 */
export const episodes: Episode[] = [
  ...rolling,
  ...archive.filter((a) => !rolling.some((r) => r.link === a.link)),
].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

/**
 * Legacy positional lookup. Retained because `/podcast/:index` URLs are indexed and
 * must keep resolving — the route uses this only to issue a permanent redirect to the
 * episode's slug, and the URL-lock guard test asserts the mapping never drifts.
 */
export const getEpisode = (index: number): Episode | undefined => {
  if (!Number.isInteger(index) || index < 0) return undefined;
  // Resolve through the FROZEN MAP, never by indexing `episodes`. The exported array is
  // the rolling feed merged with the historical supplement and re-sorted by date, so its
  // positions no longer correspond to the legacy `/podcast/:index` contract. The frozen
  // map is the only record of what each legacy index meant.
  const frozen = slugEntries.find((e) => e.index === index);
  return frozen ? getEpisodeBySlug(frozen.slug) : undefined;
};

/** Canonical lookup: resolve an episode by its stable slug. */
export const getEpisodeBySlug = (slug: string): Episode | undefined =>
  episodes.find((e) => e.slug === slug);

/** Neighbouring episodes, newest-first ordering (newer = lower index). */
export function episodeNeighbours(slug: string): {
  newer?: Episode;
  older?: Episode;
} {
  const i = episodes.findIndex((e) => e.slug === slug);
  if (i === -1) return {};
  return {
    newer: i > 0 ? episodes[i - 1] : undefined,
    older: i < episodes.length - 1 ? episodes[i + 1] : undefined,
  };
}

/** Episodes grouped by "Month YYYY", newest first — the archive layout. */
export function episodesByMonth(): { month: string; episodes: Episode[] }[] {
  const groups = new Map<string, Episode[]>();
  for (const episode of episodes) {
    const [y, m] = episode.date.split('-').map(Number);
    const month =
      y && m
        ? new Date(Date.UTC(y, m - 1, 1)).toLocaleDateString('en-US', {
            month: 'long',
            year: 'numeric',
            timeZone: 'UTC',
          })
        : 'Undated';
    const bucket = groups.get(month);
    if (bucket) bucket.push(episode);
    else groups.set(month, [episode]);
  }
  return [...groups.entries()].map(([month, eps]) => ({ month, episodes: eps }));
}

/** Human date, e.g. "Jul 23, 2026". Stable across locales. */
export function episodeDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return iso;
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
}
