/**
 * Agency Data for SEO Profile Pages
 *
 * This is a subset of agencies with pain points, priorities, and spending data.
 * Full data is in Market Assassin - these pages link to MI for full access.
 */

export interface Agency {
  slug: string;
  name: string;
  abbreviation: string;
  description: string;
  // Top pain points (limited for SEO page)
  painPoints: string[];
  // Budget priorities (limited)
  priorities: string[];
  // Spending (if available)
  spending?: {
    total?: string;
    smallBusiness?: string;
    year: string;
  };
  // Related NAICS codes
  naicsCodes?: string[];
  // Parent agency (for sub-agencies)
  parent?: string;
  // Category for filtering
  category: 'defense' | 'civilian' | 'intelligence' | 'independent';
}

// Top 50 agencies with most contractor interest
export const agencies: Agency[] = [
  // DEFENSE
  {
    slug: 'dod',
    name: 'Department of Defense',
    abbreviation: 'DOD',
    description: 'The largest federal buyer, DOD procures everything from weapons systems to IT services to facility management. Small businesses have significant opportunities through set-asides and subcontracting.',
    painPoints: [
      'Cybersecurity modernization and zero-trust architecture implementation',
      'Cloud migration and DevSecOps adoption',
      'AI/ML integration for decision support',
      'JADC2 (Joint All-Domain Command and Control)',
      'Supply chain security and resilience',
    ],
    priorities: [
      '$170B in procurement funding for FY2026',
      '$6.2B for hypersonic weapons development',
      '$9.1B for Pacific Deterrence Initiative',
      '$3.7B for JADC2 initiatives',
      'CMMC 2.0 rollout mandating cybersecurity certification',
    ],
    spending: {
      total: '$470B',
      smallBusiness: '$99.7B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541330', '541611', '541519', '236220'],
    category: 'defense',
  },
  {
    slug: 'navy',
    name: 'Department of the Navy',
    abbreviation: 'NAVY',
    description: 'Navy contracts span shipbuilding, aviation, IT systems, and base support. Opportunities exist for small businesses in maintenance, logistics, and technology.',
    painPoints: [
      'Shipyard modernization and maintenance backlogs',
      'Undersea warfare technology development',
      'Cybersecurity for naval systems',
      'Autonomous systems and unmanned vehicles',
      'Workforce recruitment and retention',
    ],
    priorities: [
      'Columbia-class submarine program',
      'Virginia-class Block V production',
      'MQ-25 Stingray unmanned refueling',
      'F/A-18 Super Hornet Block III upgrades',
      'Zero Trust Architecture implementation',
    ],
    spending: {
      total: '$154B',
      smallBusiness: '$18.2B',
      year: 'FY2025',
    },
    naicsCodes: ['336611', '541512', '541330', '488310', '236220'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'army',
    name: 'Department of the Army',
    abbreviation: 'ARMY',
    description: 'Army procurement includes vehicles, weapons, communications, and base operations. Strong small business programs and mentor-protégé opportunities.',
    painPoints: [
      'Vehicle modernization programs',
      'Network modernization and tactical communications',
      'Sustainment and logistics optimization',
      'Installation energy resilience',
      'Recruiting and retention challenges',
    ],
    priorities: [
      'Optionally Manned Fighting Vehicle (OMFV)',
      'Long-Range Precision Fires (LRPF)',
      'Future Vertical Lift (FVL)',
      'Integrated Tactical Network (ITN)',
      'Army Cloud Plan implementation',
    ],
    spending: {
      total: '$165B',
      smallBusiness: '$21.3B',
      year: 'FY2025',
    },
    naicsCodes: ['336992', '541512', '541330', '561210', '236220'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'air-force',
    name: 'Department of the Air Force',
    abbreviation: 'USAF',
    description: 'Air Force contracts cover aircraft, space systems, cybersecurity, and base support. Growing opportunities in space, cyber, and AI.',
    painPoints: [
      'Fighter aircraft modernization and sustainment',
      'Space domain awareness and resilience',
      'Cyber warfare capabilities',
      'Pilot retention and training',
      'Depot maintenance backlogs',
    ],
    priorities: [
      'Next Generation Air Dominance (NGAD)',
      'B-21 Raider bomber program',
      'Sentinel ICBM modernization',
      'Space Force growth and resilience',
      'AI and autonomous systems integration',
    ],
    spending: {
      total: '$145B',
      smallBusiness: '$17.8B',
      year: 'FY2025',
    },
    naicsCodes: ['336411', '541512', '541330', '488190', '561210'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'usace',
    name: 'U.S. Army Corps of Engineers',
    abbreviation: 'USACE',
    description: 'USACE handles military construction, civil works, and environmental projects. Major opportunities in construction, engineering, and environmental services.',
    painPoints: [
      'Infrastructure resilience and climate adaptation',
      'Dam safety and rehabilitation',
      'Military construction (MILCON) backlogs',
      'Environmental restoration',
      'Digital project management and BIM',
    ],
    priorities: [
      '$7.6B for Civil Works in FY2025',
      '$2.5B Bipartisan Infrastructure Law funding',
      '$1.8B for harbor maintenance',
      'MILCON projects at Indo-Pacific bases',
      'Climate resilience investments',
    ],
    spending: {
      total: '$12.8B',
      smallBusiness: '$4.2B',
      year: 'FY2025',
    },
    naicsCodes: ['237990', '541330', '562910', '236220', '541620'],
    parent: 'dod',
    category: 'defense',
  },
  // CIVILIAN
  {
    slug: 'va',
    name: 'Department of Veterans Affairs',
    abbreviation: 'VA',
    description: 'VA is the second-largest federal agency and a major contractor for healthcare, IT, construction, and support services. Strong veteran-owned small business preferences.',
    painPoints: [
      'Electronic health records modernization',
      'Claims processing backlog',
      'Facility modernization and construction',
      'Telehealth expansion',
      'Workforce recruitment and retention',
    ],
    priorities: [
      '$60.8B in contract awards (FY2023)',
      'Oracle Cerner EHR implementation',
      'PACT Act healthcare expansion',
      'Infrastructure improvements under IRA',
      'Caregiver support program expansion',
    ],
    spending: {
      total: '$60.8B',
      smallBusiness: '$18.5B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '621111', '236220', '561320', '541611'],
    category: 'civilian',
  },
  {
    slug: 'dhs',
    name: 'Department of Homeland Security',
    abbreviation: 'DHS',
    description: 'DHS contracts span border security, cybersecurity, emergency management, and transportation security. Growing focus on technology and infrastructure.',
    painPoints: [
      'Border security technology and infrastructure',
      'Cybersecurity for critical infrastructure',
      'Legacy IT system modernization',
      'Disaster response capabilities',
      'Workforce recruitment for cyber roles',
    ],
    priorities: [
      'Border wall and technology systems',
      'CISA cybersecurity programs',
      'FEMA disaster preparedness',
      'TSA checkpoint modernization',
      'Coast Guard fleet recapitalization',
    ],
    spending: {
      total: '$28.5B',
      smallBusiness: '$7.2B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541519', '561612', '541330', '561210'],
    category: 'civilian',
  },
  {
    slug: 'hhs',
    name: 'Department of Health and Human Services',
    abbreviation: 'HHS',
    description: 'HHS oversees healthcare programs including Medicare, Medicaid, NIH research, CDC, and FDA. Opportunities in IT, research, and healthcare services.',
    painPoints: [
      'Health IT interoperability',
      'Pandemic preparedness',
      'Drug and medical device oversight',
      'Healthcare fraud prevention',
      'Research data management',
    ],
    priorities: [
      'NIH research funding ($47B+)',
      'CDC modernization',
      'FDA digital transformation',
      'CMS payment system updates',
      'BARDA medical countermeasures',
    ],
    spending: {
      total: '$32.1B',
      smallBusiness: '$6.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541714', '541711', '541720', '621111'],
    category: 'civilian',
  },
  {
    slug: 'gsa',
    name: 'General Services Administration',
    abbreviation: 'GSA',
    description: 'GSA manages government buildings and provides acquisition services. The GSA Schedule is a major pathway for selling to all federal agencies.',
    painPoints: [
      'Federal building modernization',
      'Workplace transformation',
      'Electric vehicle fleet transition',
      'Acquisition innovation',
      'Small business utilization',
    ],
    priorities: [
      'Public Buildings Service modernization',
      'GSA Schedule simplification',
      'Technology Transformation Services growth',
      'Sustainability and net-zero buildings',
      'Buy American compliance',
    ],
    spending: {
      total: '$18.3B',
      smallBusiness: '$8.1B',
      year: 'FY2025',
    },
    naicsCodes: ['531120', '541512', '236220', '541611', '541330'],
    category: 'civilian',
  },
  {
    slug: 'nasa',
    name: 'National Aeronautics and Space Administration',
    abbreviation: 'NASA',
    description: 'NASA contracts cover space exploration, aeronautics research, and technology development. Strong SBIR/STTR programs for small businesses.',
    painPoints: [
      'Artemis lunar program execution',
      'Commercial crew and cargo partnerships',
      'Climate research and Earth observation',
      'Deep space communications',
      'Workforce STEM pipeline',
    ],
    priorities: [
      'Artemis Moon-to-Mars program',
      'Space Launch System (SLS)',
      'Gateway lunar station',
      'Commercial LEO destinations',
      'Earth science satellite missions',
    ],
    spending: {
      total: '$22.1B',
      smallBusiness: '$3.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541715', '336414', '541512', '541330', '541714'],
    category: 'civilian',
  },
  {
    slug: 'doe',
    name: 'Department of Energy',
    abbreviation: 'DOE',
    description: 'DOE manages national laboratories, nuclear weapons, and clean energy programs. Opportunities in R&D, construction, and environmental cleanup.',
    painPoints: [
      'Nuclear weapons modernization',
      'Clean energy technology deployment',
      'National laboratory infrastructure',
      'Grid modernization and resilience',
      'Environmental cleanup legacy sites',
    ],
    priorities: [
      'NNSA weapons modernization',
      'CHIPS Act advanced manufacturing',
      'Bipartisan Infrastructure Law projects',
      'Inflation Reduction Act clean energy',
      'Fusion energy research',
    ],
    spending: {
      total: '$42.5B',
      smallBusiness: '$5.2B',
      year: 'FY2025',
    },
    naicsCodes: ['541712', '541330', '541714', '237130', '562910'],
    category: 'civilian',
  },
  {
    slug: 'state',
    name: 'Department of State',
    abbreviation: 'STATE',
    description: 'State Department contracts cover embassy construction, security, IT, and foreign assistance. Opportunities for global logistics and support services.',
    painPoints: [
      'Embassy security and construction',
      'IT modernization and cybersecurity',
      'Consular services technology',
      'Foreign assistance program delivery',
      'Diplomatic workforce support',
    ],
    priorities: [
      'Embassy security upgrades',
      'IT infrastructure modernization',
      'Global supply chain management',
      'Foreign assistance implementation',
      'Climate diplomacy initiatives',
    ],
    spending: {
      total: '$14.2B',
      smallBusiness: '$2.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '236220', '561612', '541611', '561210'],
    category: 'civilian',
  },
  {
    slug: 'dot',
    name: 'Department of Transportation',
    abbreviation: 'DOT',
    description: 'DOT oversees highways, aviation, rail, and transit. Bipartisan Infrastructure Law creating major opportunities in construction and technology.',
    painPoints: [
      'Highway and bridge infrastructure',
      'Aviation system modernization',
      'Rail safety improvements',
      'Transit system expansion',
      'Emerging transportation technology',
    ],
    priorities: [
      'Bipartisan Infrastructure Law implementation',
      'FAA NextGen air traffic modernization',
      'Electric vehicle infrastructure',
      'High-speed rail development',
      'Autonomous vehicle integration',
    ],
    spending: {
      total: '$78.5B',
      smallBusiness: '$8.9B',
      year: 'FY2025',
    },
    naicsCodes: ['237310', '541330', '541512', '488490', '236220'],
    category: 'civilian',
  },
  {
    slug: 'epa',
    name: 'Environmental Protection Agency',
    abbreviation: 'EPA',
    description: 'EPA contracts cover environmental cleanup, monitoring, research, and regulatory support. Strong small business utilization in environmental services.',
    painPoints: [
      'PFAS contamination remediation',
      'Water infrastructure aging',
      'Air quality monitoring',
      'Climate change adaptation',
      'Environmental justice implementation',
    ],
    priorities: [
      'Infrastructure Investment and Jobs Act funding',
      'Inflation Reduction Act climate programs',
      'Superfund cleanups',
      'Clean water initiatives',
      'Environmental data modernization',
    ],
    spending: {
      total: '$6.8B',
      smallBusiness: '$2.1B',
      year: 'FY2025',
    },
    naicsCodes: ['541620', '562910', '541330', '541380', '541512'],
    category: 'civilian',
  },
  // Sub-agencies with high spending
  {
    slug: 'navfac',
    name: 'Naval Facilities Engineering Systems Command',
    abbreviation: 'NAVFAC',
    description: 'NAVFAC manages Navy and Marine Corps construction, facilities, and environmental programs. Major opportunities in construction, A-E services, and base operations.',
    painPoints: [
      'Infrastructure modernization and facility upgrades',
      'Energy efficiency and renewable energy projects',
      'Climate resilience and sea-level rise adaptation',
      'Shipyard modernization (SIOP)',
      'Disaster recovery and emergency response',
    ],
    priorities: [
      '$2.3B for MILCON projects',
      '$1.5B Shipyard Infrastructure Optimization Program',
      '$1.1B infrastructure resilience projects',
      '$950M in MACC task orders',
      '$500M energy efficiency projects',
    ],
    spending: {
      total: '$8.2B',
      smallBusiness: '$3.1B',
      year: 'FY2025',
    },
    naicsCodes: ['236220', '541330', '237990', '562910', '238210'],
    parent: 'navy',
    category: 'defense',
  },
  {
    slug: 'navsea',
    name: 'Naval Sea Systems Command',
    abbreviation: 'NAVSEA',
    description: 'NAVSEA is the largest Navy command, responsible for shipbuilding, maintenance, and weapons systems. Opportunities for ship repair, engineering, and technology.',
    painPoints: [
      'Ship design and engineering modernization',
      'Maintenance and repair optimization',
      'Submarine and surface ship modernization',
      'Nuclear propulsion sustainment',
      'Supply chain management',
    ],
    priorities: [
      '$2.3B Columbia-class submarine program',
      '$1.1B Virginia-class Block V production',
      '$850M DDG-51 modernization',
      '$500M Shipyard Infrastructure Optimization',
      '$400M autonomous vehicle development',
    ],
    spending: {
      total: '$35.2B',
      smallBusiness: '$4.8B',
      year: 'FY2025',
    },
    naicsCodes: ['336611', '541330', '488310', '541512', '332312'],
    parent: 'navy',
    category: 'defense',
  },
  {
    slug: 'navair',
    name: 'Naval Air Systems Command',
    abbreviation: 'NAVAIR',
    description: 'NAVAIR manages Navy and Marine Corps aircraft, weapons, and aviation systems. Opportunities in aviation maintenance, engineering, and technology.',
    painPoints: [
      'Aircraft modernization and sustainment',
      'Unmanned aerial systems development',
      'Avionics and sensor integration',
      'Training systems and simulators',
      'Digital engineering and MBE',
    ],
    priorities: [
      '$1.8B F/A-18 Super Hornet Block III',
      '$1.2B CH-53K King Stallion production',
      '$1.1B F-35 sustainment',
      '$900M MQ-25 Stingray program',
      '$750M Next Generation Jammer',
    ],
    spending: {
      total: '$28.5B',
      smallBusiness: '$3.9B',
      year: 'FY2025',
    },
    naicsCodes: ['336411', '541330', '541512', '611512', '488190'],
    parent: 'navy',
    category: 'defense',
  },
  {
    slug: 'disa',
    name: 'Defense Information Systems Agency',
    abbreviation: 'DISA',
    description: 'DISA provides IT and communications support to DOD and combat commands. Major opportunities in cybersecurity, cloud, and network services.',
    painPoints: [
      'Zero Trust Architecture implementation',
      'Cloud migration (milCloud)',
      'Unified communications modernization',
      'Cybersecurity operations',
      'Network modernization',
    ],
    priorities: [
      'JADC2 network integration',
      'Thunderdome zero trust platform',
      'Defense Enclave Services (DES)',
      'Enterprise cloud services',
      'Cybersecurity service provider (CSSP)',
    ],
    spending: {
      total: '$8.9B',
      smallBusiness: '$1.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541519', '517110', '541330', '541511'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'dla',
    name: 'Defense Logistics Agency',
    abbreviation: 'DLA',
    description: 'DLA manages the global supply chain for DOD. Opportunities in logistics, distribution, and commodities from fuel to food to medical supplies.',
    painPoints: [
      'Supply chain resilience',
      'Inventory management optimization',
      'Distribution network modernization',
      'Strategic material stockpile management',
      'Fuel and energy security',
    ],
    priorities: [
      'Supply chain risk management (SCRM)',
      'Domestic sourcing initiatives',
      'Warehouse modernization',
      'Enterprise Business System (EBS) upgrades',
      'Contested logistics capability',
    ],
    spending: {
      total: '$42.8B',
      smallBusiness: '$8.5B',
      year: 'FY2025',
    },
    naicsCodes: ['493110', '423860', '324110', '339113', '423450'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'fema',
    name: 'Federal Emergency Management Agency',
    abbreviation: 'FEMA',
    description: 'FEMA coordinates disaster response and preparedness. Opportunities in emergency services, logistics, construction, and IT.',
    painPoints: [
      'Disaster response capacity',
      'Grant management modernization',
      'Climate adaptation planning',
      'Workforce readiness',
      'Supply chain pre-positioning',
    ],
    priorities: [
      'Disaster Relief Fund management',
      'Hazard Mitigation Grant Program',
      'Building Resilient Infrastructure and Communities (BRIC)',
      'National Flood Insurance Program modernization',
      'Public Assistance process improvement',
    ],
    spending: {
      total: '$28.5B',
      smallBusiness: '$5.2B',
      year: 'FY2025',
    },
    naicsCodes: ['541611', '561210', '484110', '541512', '236220'],
    parent: 'dhs',
    category: 'civilian',
  },
  {
    slug: 'cbp',
    name: 'U.S. Customs and Border Protection',
    abbreviation: 'CBP',
    description: 'CBP manages border security and trade enforcement. Opportunities in surveillance technology, infrastructure, IT, and support services.',
    painPoints: [
      'Border surveillance technology',
      'Port of entry modernization',
      'Trade facilitation systems',
      'Workforce support services',
      'Aircraft and vehicle fleet',
    ],
    priorities: [
      'Integrated surveillance towers',
      'Non-intrusive inspection technology',
      'Automated Commercial Environment (ACE)',
      'Air and Marine Operations assets',
      'Personnel support services',
    ],
    spending: {
      total: '$18.2B',
      smallBusiness: '$3.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541519', '561612', '336411', '541330'],
    parent: 'dhs',
    category: 'civilian',
  },
  {
    slug: 'uscg',
    name: 'U.S. Coast Guard',
    abbreviation: 'USCG',
    description: 'Coast Guard contracts cover maritime security, search and rescue, and environmental protection. Opportunities in shipbuilding, aviation, and IT.',
    painPoints: [
      'Cutter fleet recapitalization',
      'Aviation asset modernization',
      'Shore infrastructure aging',
      'IT system modernization',
      'Workforce housing and support',
    ],
    priorities: [
      'Polar Security Cutter program',
      'Offshore Patrol Cutter production',
      'HC-130J aircraft acquisition',
      'Command and control systems',
      'Shore facility improvements',
    ],
    spending: {
      total: '$2.8B',
      smallBusiness: '$680M',
      year: 'FY2025',
    },
    naicsCodes: ['336611', '336411', '541512', '541330', '236220'],
    parent: 'dhs',
    category: 'civilian',
  },
  {
    slug: 'cisa',
    name: 'Cybersecurity and Infrastructure Security Agency',
    abbreviation: 'CISA',
    description: 'CISA leads federal cybersecurity and critical infrastructure protection. Growing opportunities in cybersecurity services and technology.',
    painPoints: [
      'Critical infrastructure protection',
      'Federal network security',
      'Election security',
      'Ransomware prevention',
      'Vulnerability management',
    ],
    priorities: [
      'Continuous Diagnostics and Mitigation (CDM)',
      'Zero Trust Architecture support',
      'Critical infrastructure resilience',
      'Cyber threat intelligence sharing',
      'Secure cloud adoption',
    ],
    spending: {
      total: '$2.9B',
      smallBusiness: '$720M',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541519', '541511', '541330', '541611'],
    parent: 'dhs',
    category: 'civilian',
  },
  {
    slug: 'nih',
    name: 'National Institutes of Health',
    abbreviation: 'NIH',
    description: 'NIH is the largest biomedical research funder in the world. Opportunities in research services, lab construction, IT, and scientific support.',
    painPoints: [
      'Research data management',
      'Clinical trial infrastructure',
      'Lab facility modernization',
      'IT security and compliance',
      'Research workforce development',
    ],
    priorities: [
      'ARPA-H health research',
      'Cancer Moonshot initiatives',
      'Pandemic preparedness research',
      'Data sharing infrastructure',
      'Lab construction and renovation',
    ],
    spending: {
      total: '$47.5B',
      smallBusiness: '$3.2B',
      year: 'FY2025',
    },
    naicsCodes: ['541714', '541711', '541712', '541512', '236220'],
    parent: 'hhs',
    category: 'civilian',
  },
  {
    slug: 'cdc',
    name: 'Centers for Disease Control and Prevention',
    abbreviation: 'CDC',
    description: 'CDC protects public health through disease prevention and control. Opportunities in IT, lab services, public health support, and communications.',
    painPoints: [
      'Data modernization initiative',
      'Laboratory capacity expansion',
      'Workforce development',
      'Emergency preparedness',
      'IT infrastructure aging',
    ],
    priorities: [
      'Public health data modernization',
      'Lab capacity expansion',
      'Global health security',
      'Vaccination program support',
      'Chronic disease prevention',
    ],
    spending: {
      total: '$8.9B',
      smallBusiness: '$1.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541714', '541611', '541720', '541990'],
    parent: 'hhs',
    category: 'civilian',
  },
  {
    slug: 'fda',
    name: 'Food and Drug Administration',
    abbreviation: 'FDA',
    description: 'FDA regulates food, drugs, medical devices, and tobacco. Opportunities in IT, scientific review support, inspection services, and lab analysis.',
    painPoints: [
      'Drug and device review modernization',
      'Food safety technology',
      'IT system modernization',
      'Inspection capacity',
      'Data analytics capabilities',
    ],
    priorities: [
      'Digital transformation initiatives',
      'Real-world evidence platforms',
      'Food supply chain tracking',
      'Tobacco regulation implementation',
      'Medical device cybersecurity',
    ],
    spending: {
      total: '$3.5B',
      smallBusiness: '$680M',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541380', '541714', '541720', '541611'],
    parent: 'hhs',
    category: 'civilian',
  },
  {
    slug: 'cms',
    name: 'Centers for Medicare & Medicaid Services',
    abbreviation: 'CMS',
    description: 'CMS administers Medicare, Medicaid, and the ACA marketplaces. Major IT contracts for claims processing and program integrity.',
    painPoints: [
      'Claims processing modernization',
      'Program integrity and fraud prevention',
      'Interoperability requirements',
      'Quality measurement systems',
      'Customer service capacity',
    ],
    priorities: [
      'Medicare Administrative Contractor (MAC) operations',
      'Healthcare.gov marketplace',
      'Quality Payment Program',
      'Price transparency implementation',
      'Unified Program Integrity Contractor (UPIC)',
    ],
    spending: {
      total: '$5.2B',
      smallBusiness: '$1.1B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '524292', '541611', '541519', '561422'],
    parent: 'hhs',
    category: 'civilian',
  },
  {
    slug: 'faa',
    name: 'Federal Aviation Administration',
    abbreviation: 'FAA',
    description: 'FAA manages the national airspace system. Opportunities in IT, air traffic control systems, airport infrastructure, and aviation safety.',
    painPoints: [
      'NextGen air traffic modernization',
      'Aging infrastructure replacement',
      'Controller workforce shortage',
      'Unmanned aircraft integration',
      'Cybersecurity for aviation systems',
    ],
    priorities: [
      'Terminal Flight Data Manager (TFDM)',
      'En Route Automation Modernization (ERAM)',
      'Airport improvement grants',
      'UAS traffic management (UTM)',
      'Space traffic management',
    ],
    spending: {
      total: '$18.2B',
      smallBusiness: '$2.8B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541330', '237310', '541618', '561210'],
    parent: 'dot',
    category: 'civilian',
  },
  {
    slug: 'irs',
    name: 'Internal Revenue Service',
    abbreviation: 'IRS',
    description: 'IRS collects federal taxes and enforces tax law. Major IT modernization underway with Inflation Reduction Act funding.',
    painPoints: [
      'Legacy IT system modernization',
      'Customer service improvement',
      'Cybersecurity and fraud prevention',
      'Document processing automation',
      'Workforce hiring and training',
    ],
    priorities: [
      '$80B Inflation Reduction Act modernization',
      'Tax processing system replacement',
      'Customer callback technology',
      'Digital services expansion',
      'Enforcement technology upgrades',
    ],
    spending: {
      total: '$12.8B',
      smallBusiness: '$2.1B',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541519', '561422', '541611', '541214'],
    parent: 'treasury',
    category: 'civilian',
  },
  {
    slug: 'ssa',
    name: 'Social Security Administration',
    abbreviation: 'SSA',
    description: 'SSA administers retirement, disability, and survivor benefits. Opportunities in IT modernization, customer service, and claims processing.',
    painPoints: [
      'IT infrastructure aging',
      'Customer service capacity',
      'Disability claims backlog',
      'Fraud prevention',
      'Workforce succession planning',
    ],
    priorities: [
      'IT Modernization Plan implementation',
      'Online services expansion',
      'Contact center improvements',
      'Anti-fraud technology',
      'Facility modernization',
    ],
    spending: {
      total: '$2.8B',
      smallBusiness: '$580M',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '561422', '541519', '541611', '518210'],
    category: 'independent',
  },
  {
    slug: 'sba',
    name: 'Small Business Administration',
    abbreviation: 'SBA',
    description: 'SBA supports small businesses through loans, contracting assistance, and disaster relief. Key partner for government contracting programs.',
    painPoints: [
      'Loan processing technology',
      'Disaster assistance capacity',
      'Contracting program oversight',
      'Customer service modernization',
      'Data analytics capabilities',
    ],
    priorities: [
      'Lending platform modernization',
      'Disaster loan processing',
      'Certification programs (8(a), HUBZone, WOSB)',
      'Government contracting support',
      'Entrepreneurial development',
    ],
    spending: {
      total: '$1.2B',
      smallBusiness: '$480M',
      year: 'FY2025',
    },
    naicsCodes: ['541512', '541611', '522390', '541519', '561499'],
    category: 'independent',
  },
  {
    slug: 'darpa',
    name: 'Defense Advanced Research Projects Agency',
    abbreviation: 'DARPA',
    description: 'DARPA develops breakthrough technologies for national security. Known for high-risk, high-reward R&D with significant small business opportunities.',
    painPoints: [
      'Accelerating technology transition',
      'Emerging technology competition',
      'AI/ML advancement',
      'Hypersonic technology development',
      'Biotechnology applications',
    ],
    priorities: [
      'AI Next campaign',
      'Microelectronics research',
      'Hypersonic systems',
      'Biological technologies',
      'Quantum information science',
    ],
    spending: {
      total: '$4.2B',
      smallBusiness: '$1.1B',
      year: 'FY2025',
    },
    naicsCodes: ['541715', '541712', '541714', '541330', '541511'],
    parent: 'dod',
    category: 'defense',
  },
  {
    slug: 'nsf',
    name: 'National Science Foundation',
    abbreviation: 'NSF',
    description: 'NSF funds fundamental research across all scientific disciplines. Strong SBIR/STTR programs for technology commercialization.',
    painPoints: [
      'Research infrastructure modernization',
      'STEM workforce development',
      'Research data management',
      'Emerging technology research',
      'International collaboration',
    ],
    priorities: [
      'CHIPS and Science Act implementation',
      'AI research institutes',
      'Quantum science centers',
      'Climate research',
      'Research security',
    ],
    spending: {
      total: '$9.5B',
      smallBusiness: '$850M',
      year: 'FY2025',
    },
    naicsCodes: ['541712', '541715', '541714', '541511', '541330'],
    category: 'independent',
  },
];

// Helper to get agency by slug
export function getAgencyBySlug(slug: string): Agency | undefined {
  return agencies.find(a => a.slug === slug);
}

// Get all agency slugs for static generation
export function getAllAgencySlugs(): string[] {
  return agencies.map(a => a.slug);
}

// Get agencies by category
export function getAgenciesByCategory(category: Agency['category']): Agency[] {
  return agencies.filter(a => a.category === category);
}

// Get sub-agencies
export function getSubAgencies(parentSlug: string): Agency[] {
  return agencies.filter(a => a.parent === parentSlug);
}
